export interface Product {
  id: string;
  name: string;
  slug: string;
  subtitle?: string;
  code: string;
  price?: string;
  surface: string;
  thickness: string;
  size: string;
  finish: string;
  color: string;
  applications?: string[];
  collection?: string;
  catalogueUrl?: string;
  description?: string;
  images: string[];
  url: string;
}

export const products: Product[] = [
  {
    "id": "1",
    "name": "Corchia",
    "slug": "corchia",
    "code": "ST65",
    "price": "Liên Hệ",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Màu Be",
    "catalogueUrl": "https://drive.google.com/uc?id=1QonkfbgSmO_I78ziRXBq_HkkspkUDRHP",
    "description": "Công nghệ xuyên sáng cùng khổ lớn vượt giới hạn giúp các sản phẩm trong BST Luce Tech đạt được vẻ đẹp chân thực của tự nhiên.",
    "images": []
  },
  {
    "id": "2",
    "name": "Venato",
    "slug": "venato",
    "code": "ST64",
    "price": "Liên Hệ",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Bóng kính",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "Công nghệ xuyên sáng cùng khổ lớn vượt giới hạn giúp các sản phẩm trong BST Luce Tech đạt được vẻ đẹp chân thực của tự nhiên.",
    "images": []
  },
  {
    "id": "3",
    "name": "Wavy",
    "slug": "wavy",
    "code": "ST66",
    "price": "Liên Hệ",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Màu Be",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "Công nghệ xuyên sáng cùng khổ lớn vượt giới hạn giúp các sản phẩm trong BST Luce Tech đạt được vẻ đẹp chân thực của tự nhiên.",
    "images": []
  },
  {
    "id": "4",
    "name": "Honey Onyx",
    "slug": "honey-onyx",
    "code": "ST61",
    "price": "Liên Hệ",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Màu Be",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Công nghệ xuyên sáng cùng khổ lớn vượt giới hạn giúp các sản phẩm trong BST Luce Tech đạt được vẻ đẹp chân thực của tự nhiên. Những đường vân tròn mềm mại của Honey Onyx đem lại sự thư thái",
    "images": []
  },
  {
    "id": "5",
    "name": "Arabescato Antique",
    "slug": "arabescato-antique",
    "code": "ST62",
    "price": "Liên Hệ",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Trắng",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Công nghệ xuyên sáng cùng khổ lớn vượt giới hạn giúp các sản phẩm trong BST Luce Tech đạt được vẻ đẹp chân thực của tự nhiên. Những đường vân cá tính",
    "images": []
  },
  {
    "id": "6",
    "name": "Alpinus",
    "slug": "alpinus",
    "code": "SP25",
    "price": "1800000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Màu Be",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Alpinus độc đáo với hoa văn giống như pha lê. Với sự bùng nổ của màu trắng",
    "images": []
  },
  {
    "id": "7",
    "name": "Kanjini",
    "slug": "kanjini",
    "code": "SP07",
    "price": "1800000/m²",
    "surface": "Đá",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Xám trắng",
    "catalogueUrl": "",
    "description": "Tone màu xám với hoàn thiện bóng giúp tăng diện tích không gian của bạn nhưng vẫn giữ được sự mộc mạc tối giản",
    "images": []
  },
  {
    "id": "8",
    "name": "Panda White",
    "slug": "panda-white",
    "code": "SP09",
    "price": "1800000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm|15mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Trắng|Đen",
    "catalogueUrl": "",
    "images": []
  },
  {
    "id": "9",
    "name": "Nebula",
    "slug": "nebula",
    "code": "SP11",
    "price": "1800000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Xám",
    "catalogueUrl": "",
    "description": "\"Cảm hứng từ những tinh vân vũ trụ đã được bao trọn trong thiết kế độc đáo của NEBULA. Phải mất nhiều năm để hình thành nên những tinh vân tuyệt đẹp trong thiên hà",
    "images": []
  },
  {
    "id": "10",
    "name": "Ofanto",
    "slug": "ofanto",
    "code": "SP12",
    "price": "1800000/m²",
    "surface": "Đá",
    "thickness": "9mm|15mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Xám trắng",
    "catalogueUrl": "",
    "description": "\"Mạnh mẽ và táo bạo",
    "images": []
  },
  {
    "id": "11",
    "name": "Blue Explosion",
    "slug": "blue-explosion",
    "code": "SP13",
    "price": "1800000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm|15mm",
    "size": "1200x2400",
    "finish": "Bóng kính|Matt",
    "color": "Xanh Dương",
    "catalogueUrl": "",
    "description": "\"Lấy cảm hứng từ một loại đá quý cẩm thạch màu xanh có một bề mặt độc ​​đáo",
    "images": []
  },
  {
    "id": "12",
    "name": "Sand",
    "slug": "sand",
    "code": "SP51",
    "price": "1100000–1970000/m²",
    "surface": "BODYTECH",
    "thickness": "9mm|12mm|15mm",
    "size": "800x1600|1200x2400",
    "finish": "Bóng kính|Bóng mờ|Matt",
    "color": "Màu Be",
    "catalogueUrl": "",
    "description": "Sản phẩm Sand là sự kết hợp của các tông màu tự nhiên truyền tải chiều sâu và chi tiết thiết kế thú vị. Phản ánh sự hòa quyện mềm mại của cồn cát với tiếng thì thầm của pha lê. Tông màu ấm áp tự nhiên của sản phẩm này tôn lên mọi khu vực xung quanh cả trong nhà lẫn ngoài trời.",
    "images": []
  },
  {
    "id": "13",
    "name": "Cosima Bei",
    "slug": "cosima-bei",
    "code": "SM05",
    "price": "1800000/m²",
    "surface": "Màu Đặc",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Matt",
    "color": "Màu Be",
    "catalogueUrl": "",
    "description": "Mẫu Beige nhẹ nhàng này tạo nên một cảm giác ấm cúng cho phong cách thiết kế tối giản",
    "images": []
  },
  {
    "id": "14",
    "name": "Cosima Grey",
    "slug": "cosima-grey",
    "code": "SM04",
    "price": "1800000/m²",
    "surface": "Màu Đặc",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Matt",
    "color": "Xám",
    "catalogueUrl": "",
    "description": "\"Với tone màu xám nhạt",
    "images": []
  },
  {
    "id": "15",
    "name": "Glenveal",
    "slug": "glenveal",
    "code": "SM06",
    "price": "1800000/m²",
    "surface": "Đá",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Matt",
    "color": "Xám",
    "catalogueUrl": "",
    "description": "Bề mặt Matt tạo nên cảm giác chân thực và có độ sâu với thiết kế đá của Glenveal. Phù hợp với không gian hiện đại và tối giản",
    "images": []
  },
  {
    "id": "16",
    "name": "Stream",
    "slug": "stream",
    "code": "SM52",
    "price": "3050000/m²",
    "surface": "Đá hoa",
    "thickness": "20mm",
    "size": "1200x2400",
    "finish": "Matt",
    "color": "Trắng",
    "catalogueUrl": "",
    "description": "\"Gần với tự nhiên là xu hướng thẩm mỹ đang được ưa chuộng trong những năm gần đây. Ứng dụng công nghệ VEINTECH",
    "images": []
  },
  {
    "id": "17",
    "name": "Crater",
    "slug": "crater",
    "code": "SP31",
    "price": "1800000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Nâu",
    "catalogueUrl": "",
    "description": "\"Thiết kế ấn tượng bởi các tone màu mạnh mẽ",
    "images": []
  },
  {
    "id": "18",
    "name": "Fossil Noir",
    "slug": "fossil-noir",
    "code": "SP32",
    "price": "1800000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Đen",
    "catalogueUrl": "",
    "description": "\"Như những dòng dung nham từ núi lửa",
    "images": []
  },
  {
    "id": "19",
    "name": "Dark Emperador",
    "slug": "dark-emperador",
    "code": "SP15",
    "price": "970000–1890000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm|12mm|15mm",
    "size": "800x1600|800x2400|1200x2400",
    "finish": "Bóng kính|Bóng mờ|Matt",
    "color": "Màu Be",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "images": []
  },
  {
    "id": "20",
    "name": "Calatorao Gris",
    "slug": "calatorao-gris",
    "code": "SN54",
    "price": "1100000–1390000/m²",
    "surface": "Đá hoa",
    "thickness": "12mm|15mm",
    "size": "800x1600",
    "finish": "Matt",
    "color": "Đen",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Nằm trong BST Marble",
    "images": []
  },
  {
    "id": "21",
    "name": "Calacatta Statuario",
    "slug": "calacatta-statuario",
    "code": "SH14",
    "price": "970000/m²",
    "surface": "Đá hoa",
    "thickness": "15mm",
    "size": "800x1600",
    "finish": "Bóng mờ",
    "color": "Trắng",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "images": []
  },
  {
    "id": "22",
    "name": "Marine",
    "slug": "marine",
    "code": "SP16",
    "price": "970000–1800000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm|12mm",
    "size": "800x1600|1200x2400",
    "finish": "Bóng kính",
    "color": "Xanh Dương",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "images": []
  },
  {
    "id": "23",
    "name": "Onice Nero",
    "slug": "onice-nero",
    "code": "SP45",
    "price": "1800000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Đen",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Lấy cảm hứng từ loại đá quý màu đen truyền thống",
    "images": []
  },
  {
    "id": "24",
    "name": "Verde Karzai",
    "slug": "verde-karzai",
    "code": "SP48",
    "price": "1800000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Xanh Lá",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Verde Kazai lấy cảm hứng từ màu xanh của cây nhiệt đới",
    "images": []
  },
  {
    "id": "25",
    "name": "Carrara Bianco",
    "slug": "carrara-bianco",
    "code": "SP47",
    "price": "1800000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Trắng",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Biến đổi không gian của bạn với sản phẩm đá Carrara Bianco tinh xảo nổi bật với những khối lớn với những đường vân màu xám nhạt đan xen trên nền trắng",
    "images": []
  },
  {
    "id": "26",
    "name": "Calacatta Macchia Vecchia",
    "slug": "calacatta-macchia-vecchia",
    "code": "SP43",
    "price": "1800000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Màu Be",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "Màu Beige trang nhã kết hợp với các đường vân độc đáo tạo nên sự hài hòa và đột phá cho không gian sử dụng thêm phần sang trọng.",
    "images": []
  },
  {
    "id": "27",
    "name": "Orobico Gris",
    "slug": "orobico-gris",
    "code": "SP44",
    "price": "1800000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Xám",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "images": []
  },
  {
    "id": "28",
    "name": "Calatorao Bianco",
    "slug": "calatorao-bianco",
    "code": "SM41",
    "price": "1800000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Trắng",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "images": []
  },
  {
    "id": "29",
    "name": "Calatorao Noir",
    "slug": "calatorao-noir",
    "code": "SP29",
    "price": "1800000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính|Matt",
    "color": "Đen",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "Calatorao Noir tự hào có những đường vân vàng lấp lánh trên màu đá đen tuyền đậm để mang đến một mẫu có khả năng xử lý mọi loại không gian.",
    "images": []
  },
  {
    "id": "30",
    "name": "Ash Maple",
    "slug": "ash-maple",
    "code": "SM19",
    "price": "1800000/m²",
    "surface": "Gỗ",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Matt",
    "color": "Nâu",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Với khổ lớn vượt trội",
    "images": []
  },
  {
    "id": "31",
    "name": "Venus Blue",
    "slug": "venus-blue",
    "code": "SP34",
    "price": "1800000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Xanh Dương",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Khám phá sản phẩm Venus Blue độc đáo",
    "images": []
  },
  {
    "id": "32",
    "name": "Blue Apatite",
    "slug": "blue-apatite",
    "code": "SP46",
    "price": "1800000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Xanh Dương",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Tựa như dòng sông Amazon xanh biếc với những nhánh dày toả khắp",
    "images": []
  },
  {
    "id": "33",
    "name": "Orbico Noir",
    "slug": "orbico-noir",
    "code": "SP30",
    "price": "1800000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Đen",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Orobico Noir là một loại đá với thiết kế độc đáo . Nền màu xám đậm của nó được trang trí bằng các sợi màu be và caramel",
    "images": []
  },
  {
    "id": "34",
    "name": "Dark Onyx",
    "slug": "dark-onyx",
    "code": "SP28",
    "price": "1800000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Đen",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "images": []
  },
  {
    "id": "35",
    "name": "Calacatta Gold",
    "slug": "calacatta-gold",
    "code": "SP26",
    "price": "1800000–2100000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2700|1200x2400",
    "finish": "Bóng kính",
    "color": "Trắng",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Calacatta Gold với nền trắng có tính thẩm mỹ vượt thời gian. Các kỹ sư Slabstone thể hiện một lớp nền trắng nhạt tuyệt vời với những đường viền màu vàng và xám có độ dày khác nhau. Như thể đó là những nét vẽ",
    "images": []
  },
  {
    "id": "36",
    "name": "Blue Indigo",
    "slug": "blue-indigo",
    "code": "SP24",
    "price": "1800000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Xanh Dương",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Sự kết hợp hoàn hảo giữa vẻ đẹp tự nhiên của thiên nhiên và sự tinh tế trong từng chi tiết. Được lấy cảm hứng từ những dòng suối lớn với màu nước xanh uốn lượn",
    "images": []
  },
  {
    "id": "37",
    "name": "Calacatta Bianco",
    "slug": "calacatta-bianco",
    "code": "SP38",
    "price": "1800000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Trắng",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Sản phẩm đá Slabstone Calacatta Bianco là sự là một sự sáng tạo độc đáo từ dòng đá cẩm thạch nổi tiếng cùng tên của Ý",
    "images": []
  },
  {
    "id": "38",
    "name": "Venus Crema",
    "slug": "venus-crema",
    "code": "SP37",
    "price": "1800000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Màu Be",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Venus Cerema là sự kết hợp hoàn hảo giữa thiết kế tinh tế và chất lượng xuất sắc. Như một bức tranh sống động thể hiện vẻ đẹp của các dãy núi cao vút",
    "images": []
  },
  {
    "id": "39",
    "name": "Monarch",
    "slug": "monarch",
    "code": "SP35",
    "price": "1800000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Đen",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "images": []
  },
  {
    "id": "40",
    "name": "Laurent",
    "slug": "laurent",
    "code": "SP82",
    "price": "4500000/m²",
    "surface": "Đá",
    "thickness": "15mm",
    "size": "1200x2700",
    "finish": "Bóng kính|Matt",
    "color": "Ivory",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Laurent nổi bật với sắc đen đầy quyến rũ cùng những đường vân mạnh mẽ. Công nghệ Veintech tái hiện hoàn hảo vè đẹp tự nhiên",
    "images": []
  },
  {
    "id": "41",
    "name": "Tide",
    "slug": "tide",
    "code": "SP81",
    "price": "4500000/m²",
    "surface": "Đá",
    "thickness": "15mm",
    "size": "1200x2700",
    "finish": "Bóng kính|Matt",
    "color": "Ivory",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Tide nổi bật với những đường vân tinh tế đầy tự nhiên trong tông màu trắng. Công nghệ Veintech tái hiện hoàn hảo vè đẹp tự nhiên",
    "images": []
  },
  {
    "id": "42",
    "name": "Lagoon",
    "slug": "lagoon",
    "code": "SP80",
    "price": "4500000/m²",
    "surface": "Đá",
    "thickness": "15mm",
    "size": "1200x2700",
    "finish": "Bóng kính|Matt",
    "color": "Màu Be",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "Công nghệ vân xuyên xương giúp Lagoon tái hiện vẻ đẹp chân thực của tự nhiên.",
    "images": []
  },
  {
    "id": "43",
    "name": "Avory",
    "slug": "avory",
    "code": "SM69",
    "price": "2100000/m²",
    "surface": "Đá",
    "thickness": "9mm",
    "size": "1200x2700",
    "finish": "Matt",
    "color": "Ivory",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Avory như dải lụa trắng mềm mại được điểm xuyến đường vân tinh tế",
    "images": []
  },
  {
    "id": "44",
    "name": "Andes",
    "slug": "andes",
    "code": "SM70",
    "price": "2100000/m²",
    "surface": "Đá",
    "thickness": "9mm",
    "size": "1200x2700",
    "finish": "Matt",
    "color": "Xám",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Andes",
    "images": []
  },
  {
    "id": "45",
    "name": "Lava",
    "slug": "lava",
    "code": "SM21",
    "price": "1800000/m²",
    "surface": "Xi măng",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Đen",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "Lava độc đáo và mạnh mẽ với đường vân cam như những tia sét trên nền trời đêm.",
    "images": []
  },
  {
    "id": "46",
    "name": "Calacatta Cream",
    "slug": "calacatta-cream",
    "code": "SM17",
    "price": "1800000–2100000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm|12mm",
    "size": "1200x2700|1200x2400",
    "finish": "Matt",
    "color": "Màu Be",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Calacatta Cream",
    "images": []
  },
  {
    "id": "47",
    "name": "Crema Marfil",
    "slug": "crema-marfil",
    "code": "SM60",
    "price": "1970000–2370000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm|12mm",
    "size": "1200x2400",
    "finish": "Matt",
    "color": "Màu Be",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Crema Marfil",
    "images": []
  },
  {
    "id": "48",
    "name": "Ash Carbon",
    "slug": "ash-carbon",
    "code": "SM40",
    "price": "1800000/m²",
    "surface": "Gỗ",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Matt",
    "color": "Xám",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Với khổ lớn vượt trội",
    "images": []
  },
  {
    "id": "49",
    "name": "Ash Drift",
    "slug": "ash-drift",
    "code": "SM49",
    "price": "1800000/m²",
    "surface": "Gỗ",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Nâu",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Với khổ lớn vượt trội",
    "images": []
  },
  {
    "id": "50",
    "name": "Pietra Dark",
    "slug": "pietra-dark",
    "code": "SM18",
    "price": "1800000/m²",
    "surface": "Đá",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Matt",
    "color": "Đen",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Với thiết kế độc đáo khác biệt hoàn toàn với những sản phẩm đang có mặt trên thị trường",
    "images": []
  },
  {
    "id": "51",
    "name": "Rosso Statuario",
    "slug": "rosso-statuario",
    "code": "SM39",
    "price": "1800000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Matt",
    "color": "Rose",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Rosso Statuario",
    "images": []
  },
  {
    "id": "52",
    "name": "Raw Dark",
    "slug": "raw-dark",
    "code": "SM22",
    "price": "1800000/m²",
    "surface": "Xi măng",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Matt",
    "color": "Xám trắng",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Raw Dark Stone là sự pha trộn hoàn hảo giữa bề mặt đen mịn và đường vân trắng mềm mại",
    "images": []
  },
  {
    "id": "53",
    "name": "Ash Ebony",
    "slug": "ash-ebony",
    "code": "SM23",
    "price": "1800000/m²",
    "surface": "Gỗ",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Matt",
    "color": "Xám",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Với khổ lớn vượt trội",
    "images": []
  },
  {
    "id": "54",
    "name": "Marquina",
    "slug": "marquina",
    "code": "SM20",
    "price": "1800000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm",
    "size": "1200x2400",
    "finish": "Matt",
    "color": "Đen",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Hồ Maracaibo ở Venezuela được mệnh danh là “thiên đường của những vũ điệu sấm sét” với xấp xỉ 3 triệu cú sét mỗi năm",
    "images": []
  },
  {
    "id": "55",
    "name": "Calatorao Cafe",
    "slug": "calatorao-cafe",
    "code": "SN55",
    "price": "2820000/m²",
    "surface": "Đá hoa",
    "thickness": "15mm",
    "size": "1200x2400",
    "finish": "Matt",
    "color": "",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "images": []
  },
  {
    "id": "56",
    "name": "Thunder",
    "slug": "thunder",
    "code": "SP08",
    "price": "1800000–2500000/m²",
    "surface": "Đá",
    "thickness": "9mm|15mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Màu Be|Trắng",
    "catalogueUrl": "",
    "description": "Thiết kế marble ấn tượng với những đường oxy hoá màu vàng thể hiện chân thực nhất vẻ đẹp của đá tự nhiên",
    "images": []
  },
  {
    "id": "57",
    "name": "Summer Fog",
    "slug": "summer-fog",
    "code": "SP10",
    "price": "1220000–2500000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm|15mm|20mm",
    "size": "800x1600|800x2400|1200x2400|1600x2400",
    "finish": "Bóng kính|Bóng mờ",
    "color": "Trắng",
    "catalogueUrl": "",
    "description": "Mẫu Marble trắng nhẹ nhàng với những đường vân mờ ảo như lớp sương mùa hè",
    "images": []
  },
  {
    "id": "58",
    "name": "Serpentine",
    "slug": "serpentine",
    "code": "SP27",
    "price": "1800000–2500000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm|15mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Xanh Lá",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Sự tươi mới và độc đáo của sắc xanh đã tạo nên điểm nhấn khác biệt cho thiết kế. Serpentine gợi cảm giác phóng khoáng nhưng tinh tế",
    "images": []
  },
  {
    "id": "59",
    "name": "Patagonia",
    "slug": "patagonia",
    "code": "SP36",
    "price": "1800000–2500000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm|15mm",
    "size": "1200x2400",
    "finish": "Bóng kính",
    "color": "Màu Be",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Lấy cảm hứng từ những viên đá tự nhiên",
    "images": []
  },
  {
    "id": "60",
    "name": "Feathers",
    "slug": "feathers",
    "code": "SP42",
    "price": "1800000–2500000/m²",
    "surface": "Đá hoa",
    "thickness": "9mm|15mm",
    "size": "1200x2400",
    "finish": "Bóng kính|Matt",
    "color": "Xanh Dương",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "images": []
  },
  {
    "id": "61",
    "name": "Desert",
    "slug": "desert",
    "code": "SP50",
    "price": "1970000–2820000/m²",
    "surface": "BODYTECH",
    "thickness": "9mm|15mm",
    "size": "1200x2400",
    "finish": "Bóng kính|Bóng mờ",
    "color": "Màu Be",
    "catalogueUrl": "",
    "images": []
  },
  {
    "id": "62",
    "name": "Helix Nero",
    "slug": "helix-nero",
    "code": "SP53",
    "price": "1100000–2820000/m²",
    "surface": "BODYTECH",
    "thickness": "9mm|12mm|15mm",
    "size": "800x1600|1200x2400",
    "finish": "Bóng kính",
    "color": "Đen",
    "catalogueUrl": "https://drive.google.com/uc?id=1tuT2pTEdj7GsRGCitbG4klqCr8DgwD4n",
    "description": "\"Tone màu đen huyền bí dẫn dụ sự tìm tòi",
    "images": []
  }
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find(product => product.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter(product => product.surface === category);
}

export function getProductsByColor(color: string): Product[] {
  return products.filter(product => product.color.includes(color));
}

export function getProductsByFinish(finish: string): Product[] {
  return products.filter(product => product.finish.includes(finish));
}
